# RuboCop configuration for Train plugin testing
# Enhanced testing patterns for comprehensive test suites

# Test files have naturally longer blocks
Metrics/BlockLength:
  Max: 50  # Allow longer test blocks
  AllowedMethods:
    - describe
    - context
    - it
    - shared_examples
    - shared_context
    - before
    - after
  Exclude:
    - '**/*_test.rb'
    - 'test/**/*'
    - 'spec/**/*'

# Test utilities and mock classes
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/**/*'  # MockResult, TestConnection, TestDouble classes

# Test output and debugging
Style/GlobalStdStream:
  Exclude:
    - 'test/**/*'  # puts, p, print for test debugging

# Test file operations and cleanup
Lint/NonAtomicFileOperation:
  Exclude:
    - 'test/**/*'  # Test cleanup patterns

# Security testing may use intentionally insecure patterns
Security/Open:
  Exclude:
    - 'test/security/**/*'  # Security tests may test insecure patterns

# Performance testing may have longer methods
Metrics/MethodLength:
  Exclude:
    - 'test/performance/**/*'

# Integration tests may have higher complexity
Metrics/AbcSize:
  Exclude:
    - 'test/integration/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/integration/**/*'

# Test data and fixtures
Style/WordArray:
  Exclude:
    - 'test/**/*'  # Test data arrays

Style/SymbolArray:
  Exclude:
    - 'test/**/*'  # Test symbol arrays