name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  RUBY_VERSION: '3.1.6'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: ruby
          package-name: train-juniper
          version-file: lib/train-juniper/version.rb
          
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          
      - name: Run full test suite
        run: |
          bundle exec rake test
          
      - name: Run security audit
        run: |
          gem install bundler-audit
          bundler-audit check --update
          
      - name: Run linting
        run: |
          bundle exec rubocop
          
      - name: Build and publish gem
        uses: rubygems/release-gem@v1