name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Mondays at 6 AM UTC to catch new vulnerabilities
    - cron: '0 6 * * 1'

permissions:
  contents: read
  security-events: write

env:
  RUBY_VERSION: '3.1.6'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
        
    - name: Install security tools
      run: |
        gem install bundler-audit
        bundle install --with security
        
    - name: Run dependency vulnerability scan
      run: |
        bundler-audit check --update --verbose
        echo "::notice::Dependency vulnerability scan completed successfully"
        
    - name: Run custom security checks
      run: |
        ruby security/security_scan.rb
        
      
    - name: Check for secrets in code
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified
      continue-on-error: true
        
  license-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6
        bundler-cache: true
        
    - name: Install license_finder
      run: |
        bundle install --with security
        
    - name: Run license audit
      run: |
        bundle exec license_finder --decisions-file .license_finder.yml
      continue-on-error: true # First run to generate decisions file
      
  security-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6
        bundler-cache: true
        
    - name: Run security-focused tests
      run: |
        bundle exec ruby -Ilib:test test/security/security_test.rb
        
    - name: Generate security test report
      run: |
        echo "## Security Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ All security tests passed" >> $GITHUB_STEP_SUMMARY
        echo "- Credential handling validated" >> $GITHUB_STEP_SUMMARY
        echo "- Command injection prevention tested" >> $GITHUB_STEP_SUMMARY  
        echo "- Output sanitization verified" >> $GITHUB_STEP_SUMMARY
        echo "- Mock mode security confirmed" >> $GITHUB_STEP_SUMMARY